---
ci:
  autofix_prs: false
  autoupdate_commit_msg: 'chore: pre-commit dependency update'
  skip:
    - 'actionlint'
    - 'ansible-lint'
    - 'check-github-workflows'
    - 'check-renovate'
    - 'commitlint'
    - 'gitleaks'
    - 'hadolint-docker'
    - 'kics-scan'
    - 'markdown-link-check'
    - 'markdownlint'
    - 'pyspelling'
    - 'yamllint'

repos:
  - repo: 'https://github.com/ansible/ansible-lint'
    rev: 'v25.1.3'
    hooks:
      - id: 'ansible-lint'
        stages:
          - 'pre-commit'
        additional_dependencies:
          # https://github.com/pre-commit/pre-commit/issues/1526
          # renovate: datasource=pypi
          - 'ansible-core==2.18.1'
        always_run: true
        description: 'This hook runs ansible-lint.'
        entry: 'python3 -m ansiblelint -v --force-color'
        language: 'python'
        # do not pass files to ansible-lint, see:
        # https://github.com/ansible/ansible-lint/issues/611
        pass_filenames: false
        # patch level languages are not possible, unless a corresponding symlink is created for
        # e.g. python3.12.4 -> python3.12. This would defeat the purpose of being very specific,
        # therefore limitting the language to a minor version only
        # renovate dep: datasource=python-version versioning=python depName=python
        language_version: '3.13'

  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: 'v5.0.0'
    hooks:
      - id: 'check-executables-have-shebangs'
        stages:
          - 'pre-commit'
      - id: 'check-merge-conflict'
        stages:
          - 'pre-commit'
        args:
          - '--assume-in-merge'
      - id: 'check-json'
        stages:
          - 'pre-commit'
      - id: 'check-shebang-scripts-are-executable'
        stages:
          - 'pre-commit'
      - id: 'check-symlinks'
        stages:
          - 'pre-commit'
      - id: 'check-toml'
        stages:
          - 'pre-commit'
      - id: 'check-xml'
        stages:
          - 'pre-commit'
      - id: 'debug-statements'
        stages:
          - 'pre-commit'
      - id: 'destroyed-symlinks'
        stages:
          - 'pre-commit'
      - id: 'detect-private-key'
        stages:
          - 'pre-commit'
      - id: 'end-of-file-fixer'
        stages:
          - 'pre-commit'
        exclude: '^molecule/default/files/test.file$'  # test file has no return on purpose
      - id: 'mixed-line-ending'
        stages:
          - 'pre-commit'
        args:
          - '--fix=no'
      - id: 'pretty-format-json'
        stages:
          - 'pre-commit'
        args:
          - '--no-sort-keys'
          - '--indent=2'
      - id: 'trailing-whitespace'
        stages:
          - 'pre-commit'
        args:
          - '--markdown-linebreak-ext=md'

  - repo: 'https://github.com/adrienverge/yamllint'
    rev: 'v1.37.0'
    hooks:
      - id: 'yamllint'
        stages:
          - 'pre-commit'
        pass_filenames: true
        verbose: true

  - repo: 'https://github.com/tcort/markdown-link-check'
    rev: 'v3.13.7'
    hooks:
      - id: 'markdown-link-check'
        stages:
          - 'pre-commit'
        pass_filenames: true
        verbose: true
        args:
          - '--progress'

  - repo: 'https://github.com/igorshubovych/markdownlint-cli'
    rev: 'v0.44.0'
    hooks:
      - id: 'markdownlint'
        stages:
          - 'pre-commit'
        verbose: true
        pass_filenames: true

  - repo: 'https://github.com/alessandrojcm/commitlint-pre-commit-hook'
    rev: 'v9.22.0'
    hooks:
      - id: 'commitlint'
        stages:
          - 'commit-msg'
        additional_dependencies:
          # renovate: datasource=npm
          - 'conventional-changelog-conventionalcommits@8.0.0'
          # renovate: datasource=npm
          - 'commitlint-plugin-selective-scope@1.0.1'

  - repo: 'https://github.com/pre-commit/mirrors-jshint'
    rev: 'v2.13.6'
    hooks:
      - id: 'jshint'
        stages:
          - 'pre-commit'
        types:
          - 'javascript'

  - repo: 'https://github.com/gitleaks/gitleaks'
    rev: 'v8.24.3'
    hooks:
      - id: 'gitleaks'
        stages:
          - 'pre-commit'

  - repo: 'https://github.com/Checkmarx/kics'
    rev: 'v2.1.6'
    hooks:
      - id: 'kics-scan'
        verbose: true
        stages:
          - 'pre-commit'

  - repo: 'https://github.com/python-jsonschema/check-jsonschema'
    rev: '0.33.0'
    hooks:
      - id: 'check-github-workflows'
        args:
          - '--verbose'
        verbose: true
        stages:
          - 'pre-commit'

  - repo: 'https://github.com/rhysd/actionlint'
    rev: 'v1.7.7'
    hooks:
      - id: 'actionlint'
        verbose: true
        stages:
          - 'pre-commit'

  - repo: 'https://github.com/sirosen/texthooks'
    rev: '0.6.8'
    hooks:
      - id: 'alphabetize-codeowners'
        verbose: true
        stages:
          - 'pre-commit'

      - id: 'fix-ligatures'
        verbose: true
        stages:
          - 'pre-commit'

      - id: 'fix-spaces'
        verbose: true
        stages:
          - 'pre-commit'

      - id: 'forbid-bidi-controls'
        verbose: true
        stages:
          - 'pre-commit'

  - repo: 'https://github.com/koalaman/shellcheck-precommit'
    rev: 'v0.10.0'
    hooks:
      - id: 'shellcheck'
        verbose: true
        stages:
          - 'pre-commit'

  - repo: 'https://github.com/renovatebot/pre-commit-hooks'
    rev: '39.252.0'
    hooks:
      - id: 'renovate-config-validator'
        verbose: true
        stages:
          - 'pre-commit'

  - repo: 'https://github.com/facelessuser/pyspelling'
    # once a release with the pre-commit hook definition is released, this should be replaced (current release: 2.10)
    rev: '63e4654f0be643ca0f1676227db24bb7f88dee29'
    hooks:
      - id: 'pyspelling'
        stages:
          - 'pre-commit'
        pass_filenames: false
        verbose: true

  - repo: 'https://github.com/hadolint/hadolint'
    rev: 'v2.12.0'
    hooks:
      - id: 'hadolint-docker'
        stages:
          - 'pre-commit'
        pass_filenames: true
        verbose: true
...
