---
ci:
  autofix_prs: false
  autoupdate_commit_msg: 'chore: pre-commit dependency update'
  skip:
    - 'actionlint'
    - 'ansible-lint'
    - 'check-github-workflows'
    - 'check-renovate'
    - 'commitlint'
    - 'gitleaks'
    - 'kics-scan'
    - 'markdown-link-check'
    - 'markdownlint'
    - 'pyspelling'
    - 'yamllint'

repos:
  - repo: 'https://github.com/ansible/ansible-lint'
    rev: '95382d398ea1744bf6bfa47b030f14c38b3f6957' # v24.7.0
    hooks:
      - id: 'ansible-lint'
        stages:
          - 'pre-commit'
        additional_dependencies:
          # https://github.com/pre-commit/pre-commit/issues/1526
          # renovate: datasource=pypi
          - 'ansible-core==2.16.8'
        always_run: true
        description: 'This hook runs ansible-lint.'
        entry: 'python3 -m ansiblelint -v --force-color'
        language: 'python'
        # do not pass files to ansible-lint, see:
        # https://github.com/ansible/ansible-lint/issues/611
        pass_filenames: false
        language_version: '3.11'

  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: '2c9f875913ee60ca25ce70243dc24d5b6415598c' # v4.6.0
    hooks:
      - id: 'check-executables-have-shebangs'
        stages:
          - 'pre-commit'
      - id: 'check-merge-conflict'
        stages:
          - 'pre-commit'
        args:
          - '--assume-in-merge'
      - id: 'check-json'
        stages:
          - 'pre-commit'
      - id: 'check-shebang-scripts-are-executable'
        stages:
          - 'pre-commit'
      - id: 'check-symlinks'
        stages:
          - 'pre-commit'
      - id: 'check-toml'
        stages:
          - 'pre-commit'
      - id: 'check-xml'
        stages:
          - 'pre-commit'
      - id: 'debug-statements'
        stages:
          - 'pre-commit'
      - id: 'destroyed-symlinks'
        stages:
          - 'pre-commit'
      - id: 'detect-private-key'
        stages:
          - 'pre-commit'
      - id: 'end-of-file-fixer'
        stages:
          - 'pre-commit'
        exclude: '^molecule/default/files/test.file$'  # test file has no return on purpose
      - id: 'mixed-line-ending'
        stages:
          - 'pre-commit'
        args:
          - '--fix=no'
      - id: 'pretty-format-json'
        stages:
          - 'pre-commit'
        args:
          - '--no-sort-keys'
          - '--indent=2'
      - id: 'trailing-whitespace'
        stages:
          - 'pre-commit'
        args:
          - '--markdown-linebreak-ext=md'

  - repo: 'https://github.com/adrienverge/yamllint'
    rev: '81e9f98ffd059efe8aa9c1b1a42e5cce61b640c6' # v1.35.1
    hooks:
      - id: 'yamllint'
        stages:
          - 'pre-commit'
        pass_filenames: true
        verbose: true

  - repo: 'https://github.com/tcort/markdown-link-check'
    rev: '71ccb4129a1fa86f6904f35c1b26348dfce1438d' # v3.12.2
    hooks:
      - id: 'markdown-link-check'
        stages:
          - 'pre-commit'
        pass_filenames: true
        verbose: true
        args:
          - '--progress'
          - '--config'
          - '.markdown-link-check.json'

  - repo: 'https://github.com/igorshubovych/markdownlint-cli'
    rev: 'f295829140d25717bc79368d3f966fc1f67a824f' # v0.41.0
    hooks:
      - id: 'markdownlint'
        stages:
          - 'pre-commit'
        verbose: true
        pass_filenames: true

  - repo: 'https://github.com/alessandrojcm/commitlint-pre-commit-hook'
    rev: 'v9.16.0' # v9.16.0
    hooks:
      - id: 'commitlint'
        stages:
          - 'commit-msg'
        additional_dependencies:
          # renovate: datasource=npm
          - 'conventional-changelog-conventionalcommits@8.0.0'
          # renovate: datasource=npm
          - 'commitlint-plugin-selective-scope@1.0.1'

  - repo: 'https://github.com/pre-commit/mirrors-jshint'
    rev: '882622d2d13597740358203e9f2e2ae5976cd149' # v2.13.6
    hooks:
      - id: 'jshint'
        stages:
          - 'pre-commit'
        types:
          - 'javascript'

  - repo: 'https://github.com/gitleaks/gitleaks'
    rev: '02808f45d038526bfcceebcbf6421c1047997ff9' # v8.18.4
    hooks:
      - id: 'gitleaks'
        stages:
          - 'pre-commit'

  - repo: 'https://github.com/Checkmarx/kics'
    rev: 'b014f9cc1f6ded067101a719d70e5b28307f7fb8' # v2.1.1
    hooks:
      - id: 'kics-scan'
        verbose: true
        stages:
          - 'pre-commit'

  - repo: 'https://github.com/python-jsonschema/check-jsonschema'
    rev: '5341df58c614b35cc9358bbea5e2e14ac7d7c282' # 0.29.0
    hooks:
      - id: 'check-github-workflows'
        args:
          - '--verbose'
        verbose: true
        stages:
          - 'pre-commit'

  - repo: 'https://github.com/rhysd/actionlint'
    rev: '62dc61a45fc95efe8c800af7a557ab0b9165d63b' # v1.7.1
    hooks:
      - id: 'actionlint'
        verbose: true
        stages:
          - 'pre-commit'

  - repo: 'https://github.com/sirosen/texthooks'
    rev: '529812dfe6d2447e0a35f4bd079c44120646b58c' # 0.6.6
    hooks:
      - id: 'alphabetize-codeowners'
        verbose: true
        stages:
          - 'pre-commit'

      - id: 'fix-ligatures'
        verbose: true
        stages:
          - 'pre-commit'

      - id: 'fix-spaces'
        verbose: true
        stages:
          - 'pre-commit'

      - id: 'forbid-bidi-controls'
        verbose: true
        stages:
          - 'pre-commit'

  - repo: 'https://github.com/koalaman/shellcheck-precommit'
    rev: '2491238703a5d3415bb2b7ff11388bf775372f29' # v0.10.0
    hooks:
      - id: 'shellcheck'
        verbose: true
        stages:
          - 'pre-commit'

  - repo: 'https://github.com/renovatebot/pre-commit-hooks'
    rev: 'd1b88e0c94b3172b85d165550c5f52d9cfa4a5e9' # 37.437.2
    hooks:
      - id: 'renovate-config-validator'
        verbose: true
        stages:
          - 'pre-commit'

  - repo: 'https://github.com/facelessuser/pyspelling'
    # once a release with the pre-commit hook definition is released, this should be replaced (current release: 2.10)
    rev: '63e4654f0be643ca0f1676227db24bb7f88dee29'
    hooks:
      - id: 'pyspelling'
        stages:
          - 'pre-commit'
        pass_filenames: false
        verbose: true
...
