---
- name: Include tasks to ensure all variables are defined properly
  ansible.builtin.include_tasks:
    file: assert.yml

- name: Include tasks to deploy files
  ansible.builtin.include_tasks:
    file: file_deployment.yml
  when:
    - _fd_files is defined
    - _fd_files | length > 0
