---
- name: 'Ensure molecule group is existing'
  hosts: 'localhost'
  gather_facts: false
  tasks:
    - name: 'Show existing groups'
      ansible.builtin.debug:
        var: 'groups'

    - name: 'Ensure the molecule group exists'
      ansible.builtin.assert:
        that: "'molecule' in groups"
        fail_msg: 'The molecule group was not found inside inventory groups: {{ groups }}'

- name: 'Converge'
  hosts: 'molecule'
  gather_facts: false
  roles:
    - role: 'sscheib.file_deployment'
  vars:
    fd_files:
      - src: 'test.file'
        dest: '/tmp/test.file'
        owner: 'root'
        group: 'root'
        mode: '0700'

      - content: 'test'
        dest: '/tmp/test.content'
        owner: 'root'
        group: 'root'
        mode: '0600'
...
