---
dependency:
  name: 'galaxy'
  options:
    requirements-file: 'requirements.yml'

verifier:
  name: 'ansible'
  enabled: true

driver:
  name: 'default'
  options:
    managed: false
    login_cmd_template: 'podman exec -it {instance} bash'
    ansible_connection_options:
      ansible_connection: 'containers.podman.podman'
      ansible_become_method: 'su'

platforms:
  - name: 'rhel10-ubi'
    # yamllint disable-line rule:line-length
    image: 'registry.access.redhat.com/ubi10/ubi:10.0-1756805986@sha256:fe8738a6e2fb7595227c058b18250ff60a8a3ea0078296d8b46e0a419738a69c'
    groups:
      - 'dnf'
    skip_versions:
      - '2.15'
      - '2.14'
      - '2.13'

  - name: 'rhel9-ubi'
    # yamllint disable-line rule:line-length
    image: 'registry.access.redhat.com/ubi9/ubi:9.6-1756915113@sha256:8f1496d50a66e41433031bf5bdedd4635520e692ccd76ffcb649cf9d30d669af'
    groups:
      - 'dnf'

  - name: 'rhel8-ubi'
    # yamllint disable-line rule:line-length
    image: 'registry.access.redhat.com/ubi8/ubi:8.10-1756195303@sha256:534c2c0efa4150ede18e3f9d7480d3b9ec2a52e62bc91cd54e08ee7336819619'
    groups:
      - 'dnf'
    skip_versions:
      - '2.18'
      - '2.17'

  - name: 'rhel7-ubi'
    # yamllint disable-line rule:line-length
    image: 'registry.access.redhat.com/ubi7/ubi:7.9-1445@sha256:dce9f8caf5b4c3a3a511f71b0e2f23a6eada9bd1c8cc3c912f0e50b6d3b824fc'
    groups:
      - 'yum'
    skip_versions:
      - '2.18'
      - '2.17'

  - name: 'debian12'
    # yamllint disable-line rule:line-length
    image: 'docker.io/debian:12.11@sha256:731dd1380d6a8d170a695dbeb17fe0eade0e1c29f654cf0a3a07f372191c3f4b'
    groups:
      - 'apt'

  - name: 'debian11'
    # yamllint disable-line rule:line-length
    image: 'docker.io/debian:11.11@sha256:8ec25a9073e8cc89a184a6256e219828196d75203375a8ad4f0977f3011f2115'
    groups:
      - 'apt'

  - name: 'debian10'
    # yamllint disable-line rule:line-length
    image: 'docker.io/debian:10.13@sha256:58ce6f1271ae1c8a2006ff7d3e54e9874d839f573d8009c20154ad0f2fb0a225'
    change_sources_list: true
    groups:
      - 'apt'
    skip_versions:
      - '2.18'

  - name: 'openwrt24.10'
    # yamllint disable-line rule:line-length
    image: 'docker.io/openwrt/rootfs:x86_64-24.10.2@sha256:3c8adad624f661f683e9e5d2977bc44fa4b29a17f76eb5c45d0aec8e079668cc'
    groups:
      - 'opkg'

  - name: 'openwrt23.05'
    # yamllint disable-line rule:line-length
    image: 'docker.io/openwrt/rootfs:x86_64-23.05.6@sha256:f53afb386d05651ada9a4a964e0779930f30962a2abc2fadf1b03bfcbcbabb14'
    groups:
      - 'opkg'

  - name: 'openwrt22.03'
    # yamllint disable-line rule:line-length
    image: 'docker.io/openwrt/rootfs:x86_64-22.03.7@sha256:f6e5b98399ae4ff89fc1a2de2da5b94c520c8f82aa1e5c717fb190da8b3313ed'
    groups:
      - 'opkg'

  - name: 'openwrt21.02'
    # yamllint disable-line rule:line-length
    image: 'docker.io/openwrt/rootfs:x86_64-21.02.7@sha256:7fc2353153c65d64a35a5fb4dc21a15bb048d812c19df3d8d4ea97745349ef79'
    groups:
      - 'opkg'

scenario:
  create_sequence:
    - 'dependency'
    - 'create'
    - 'prepare'
  check_sequence:
    - 'dependency'
    - 'destroy'
    - 'create'
    - 'prepare'
    - 'converge'
    - 'check'
    - 'destroy'
  converge_sequence:
    - 'dependency'
    - 'create'
    - 'prepare'
    - 'converge'
  destroy_sequence:
    - 'dependency'
    - 'destroy'
  test_sequence:
    - 'dependency'
    - 'destroy'
    - 'syntax'
    - 'create'
    - 'prepare'
    - 'converge'
    - 'idempotence'
    - 'verify'
    - 'destroy'
...
