---
dependency:
  name: 'galaxy'
  options:
    requirements-file: 'requirements.yml'

verifier:
  name: 'ansible'
  enabled: true

driver:
  name: 'default'
  options:
    managed: false
    login_cmd_template: 'podman exec -it {instance} bash'
    ansible_connection_options:
      ansible_connection: 'containers.podman.podman'
      ansible_become_method: 'su'

platforms:
  - name: 'rhel9-ubi'
    image: 'registry.access.redhat.com/ubi9/ubi'
    groups:
      - 'dnf'

  - name: 'rhel8-ubi'
    image: 'registry.access.redhat.com/ubi8/ubi'
    groups:
      - 'dnf'
    skip_versions:
      - '2.17'

  - name: 'rhel7-ubi'
    image: 'registry.access.redhat.com/ubi7/ubi'
    groups:
      - 'yum'
    skip_versions:
      - '2.17'

  - name: 'debian12'
    image: 'docker.io/debian:bookworm'
    groups:
      - 'apt'

  - name: 'debian11'
    image: 'docker.io/debian:bullseye'
    groups:
      - 'apt'

  - name: 'debian10'
    image: 'docker.io/debian:buster'
    groups:
      - 'apt'

  - name: 'openwrt23.05'
    image: 'docker.io/openwrt/rootfs:x86_64-openwrt-23.05'
    sysctl:
      net.ipv6.conf.all.disable_ipv6: 1
    groups:
      - 'opkg'

  - name: 'openwrt22.03.5'
    image: 'docker.io/openwrt/rootfs:x86_64-22.03.5'
    sysctl:
      net.ipv6.conf.all.disable_ipv6: 1
    groups:
      - 'opkg'

  - name: 'openwrt21.02.7'
    image: 'docker.io/openwrt/rootfs:x86_64-21.02.7'
    sysctl:
      net.ipv6.conf.all.disable_ipv6: 1
    groups:
      - 'opkg'

scenario:
  create_sequence:
    - 'dependency'
    - 'create'
    - 'prepare'
  check_sequence:
    - 'dependency'
    - 'destroy'
    - 'create'
    - 'prepare'
    - 'converge'
    - 'check'
    - 'destroy'
  converge_sequence:
    - 'dependency'
    - 'create'
    - 'prepare'
    - 'converge'
  destroy_sequence:
    - 'dependency'
    - 'destroy'
  test_sequence:
    - 'dependency'
    - 'destroy'
    - 'syntax'
    - 'create'
    - 'prepare'
    - 'converge'
    - 'idempotence'
    - 'verify'
    - 'destroy'
...
