---
dependency:
  name: 'galaxy'
  options:
    requirements-file: 'requirements.yml'

verifier:
  name: 'ansible'
  enabled: true

driver:
  name: 'default'
  options:
    managed: false
    login_cmd_template: 'podman exec -it {instance} bash'
    ansible_connection_options:
      ansible_connection: 'containers.podman.podman'
      ansible_become_method: 'su'

platforms:
  - name: 'rhel9-ubi'
    # yamllint disable-line rule:line-length
    image: 'registry.access.redhat.com/ubi9/ubi:9.5-1741600006@sha256:daafc11af246ed6445680a94357632128d25263720a1ba080a3ecdafd70aa1bd'
    groups:
      - 'dnf'

  - name: 'rhel8-ubi'
    # yamllint disable-line rule:line-length
    image: 'registry.access.redhat.com/ubi8/ubi:8.10-1184.1739756802@sha256:ab3ec0b7bb1756a09aa9b6377eddb38cee104e8f3e338f66ea82fb37742a9e94'
    groups:
      - 'dnf'
    skip_versions:
      - '2.18'
      - '2.17'

  - name: 'rhel7-ubi'
    # yamllint disable-line rule:line-length
    image: 'registry.access.redhat.com/ubi7/ubi:7.9-1445@sha256:dce9f8caf5b4c3a3a511f71b0e2f23a6eada9bd1c8cc3c912f0e50b6d3b824fc'
    groups:
      - 'yum'
    skip_versions:
      - '2.18'
      - '2.17'

  - name: 'debian12'
    # yamllint disable-line rule:line-length
    image: 'docker.io/debian:12.9@sha256:35286826a88dc879b4f438b645ba574a55a14187b483d09213a024dc0c0a64ed'
    groups:
      - 'apt'

  - name: 'debian11'
    # yamllint disable-line rule:line-length
    image: 'docker.io/debian:11.11@sha256:a6cec654bb08bdc6a563cd7507b62f57c916290e195142e79a0d41a70ebb26fa'
    groups:
      - 'apt'

  - name: 'debian10'
    # yamllint disable-line rule:line-length
    image: 'docker.io/debian:10.13@sha256:58ce6f1271ae1c8a2006ff7d3e54e9874d839f573d8009c20154ad0f2fb0a225'
    groups:
      - 'apt'
    skip_versions:
      - '2.18'

  - name: 'openwrt23.05'
    # yamllint disable-line rule:line-length
    image: 'docker.io/openwrt/rootfs:x86_64-23.05.5@sha256:a44cce5d8f3619e30b0b7cf74e236d4e62cb3bf118953f57e044dc684d7cfc36'
    groups:
      - 'opkg'

  - name: 'openwrt22.03'
    # yamllint disable-line rule:line-length
    image: 'docker.io/openwrt/rootfs:x86_64-22.03.7@sha256:f6e5b98399ae4ff89fc1a2de2da5b94c520c8f82aa1e5c717fb190da8b3313ed'
    groups:
      - 'opkg'

  - name: 'openwrt21.02'
    # yamllint disable-line rule:line-length
    image: 'docker.io/openwrt/rootfs:x86_64-21.02.7@sha256:7fc2353153c65d64a35a5fb4dc21a15bb048d812c19df3d8d4ea97745349ef79'
    groups:
      - 'opkg'

scenario:
  create_sequence:
    - 'dependency'
    - 'create'
    - 'prepare'
  check_sequence:
    - 'dependency'
    - 'destroy'
    - 'create'
    - 'prepare'
    - 'converge'
    - 'check'
    - 'destroy'
  converge_sequence:
    - 'dependency'
    - 'create'
    - 'prepare'
    - 'converge'
  destroy_sequence:
    - 'dependency'
    - 'destroy'
  test_sequence:
    - 'dependency'
    - 'destroy'
    - 'syntax'
    - 'create'
    - 'prepare'
    - 'converge'
    - 'idempotence'
    - 'verify'
    - 'destroy'
...
