---
dependency:
  name: 'galaxy'
  options:
    requirements-file: 'requirements.yml'

verifier:
  name: 'ansible'
  enabled: true

driver:
  name: 'default'
  options:
    managed: false
    login_cmd_template: 'podman exec -it {instance} bash'
    ansible_connection_options:
      ansible_connection: 'containers.podman.podman'
      ansible_become_method: 'su'

platforms:
  - name: 'rhel10-ubi'
    # yamllint disable-line rule:line-length
    image: 'registry.access.redhat.com/ubi10/ubi:10.1-1766033862@sha256:4fa402808c6dfbbb409182736ee205d774a2fa1f6f18bb9982a3f285035a8f01'
    groups:
      - 'dnf'
    skip_versions:
      - '2.15'
      - '2.14'
      - '2.13'

  - name: 'rhel9-ubi'
    # yamllint disable-line rule:line-length
    image: 'registry.access.redhat.com/ubi9/ubi:9.7-1764794285@sha256:d4feb579a84ead49894ec71fe54f14300992e202f3491d9bb22b62cc57affd49'
    groups:
      - 'dnf'

  - name: 'rhel8-ubi'
    # yamllint disable-line rule:line-length
    image: 'registry.access.redhat.com/ubi8/ubi:8.10-1766090767@sha256:ceea2c6434cc16cd796b7fcab26f351c308675bd3256894f7377262f3ed2f277'
    groups:
      - 'dnf'
    skip_versions:
      - '2.18'
      - '2.17'

  - name: 'rhel7-ubi'
    # yamllint disable-line rule:line-length
    image: 'registry.access.redhat.com/ubi7/ubi:7.9-1445@sha256:dce9f8caf5b4c3a3a511f71b0e2f23a6eada9bd1c8cc3c912f0e50b6d3b824fc'
    groups:
      - 'yum'
    skip_versions:
      - '2.18'
      - '2.17'

  - name: 'debian12'
    # yamllint disable-line rule:line-length
    image: 'docker.io/debian:12.12@sha256:7e5bc0e499a8d50cb1e32287944a90b9ec8fd7d500673e75daff3f52882f5798'
    groups:
      - 'apt'

  - name: 'debian11'
    # yamllint disable-line rule:line-length
    image: 'docker.io/debian:11.11@sha256:1b1fd1445c1d0ed68123cf76c2d7c7cb47dfdab3df56f7ff9303063110d43291'
    groups:
      - 'apt'

  - name: 'debian10'
    # yamllint disable-line rule:line-length
    image: 'docker.io/debian:10.13@sha256:58ce6f1271ae1c8a2006ff7d3e54e9874d839f573d8009c20154ad0f2fb0a225'
    change_sources_list: true
    groups:
      - 'apt'
    skip_versions:
      - '2.18'

  - name: 'openwrt24.10'
    # yamllint disable-line rule:line-length
    image: 'docker.io/openwrt/rootfs:x86_64-24.10.5@sha256:46c12e45e9071aa5afb23ee0a1cda75e6a34f49eb0cf4f6fd171c6be2ce0162f'
    groups:
      - 'opkg'

  - name: 'openwrt23.05'
    # yamllint disable-line rule:line-length
    image: 'docker.io/openwrt/rootfs:x86_64-23.05.6@sha256:f53afb386d05651ada9a4a964e0779930f30962a2abc2fadf1b03bfcbcbabb14'
    groups:
      - 'opkg'

  - name: 'openwrt22.03'
    # yamllint disable-line rule:line-length
    image: 'docker.io/openwrt/rootfs:x86_64-22.03.7@sha256:f6e5b98399ae4ff89fc1a2de2da5b94c520c8f82aa1e5c717fb190da8b3313ed'
    groups:
      - 'opkg'

  - name: 'openwrt21.02'
    # yamllint disable-line rule:line-length
    image: 'docker.io/openwrt/rootfs:x86_64-21.02.7@sha256:7fc2353153c65d64a35a5fb4dc21a15bb048d812c19df3d8d4ea97745349ef79'
    groups:
      - 'opkg'

scenario:
  create_sequence:
    - 'dependency'
    - 'create'
    - 'prepare'
  check_sequence:
    - 'dependency'
    - 'destroy'
    - 'create'
    - 'prepare'
    - 'converge'
    - 'check'
    - 'destroy'
  converge_sequence:
    - 'dependency'
    - 'create'
    - 'prepare'
    - 'converge'
  destroy_sequence:
    - 'dependency'
    - 'destroy'
  test_sequence:
    - 'dependency'
    - 'destroy'
    - 'syntax'
    - 'create'
    - 'prepare'
    - 'converge'
    - 'idempotence'
    - 'verify'
    - 'destroy'
...
