---
- name: 'Install Python in containers'
  hosts: 'apt'
  gather_facts: false

  tasks:
    - name: 'Include tasks to filter incompatible platforms'
      ansible.builtin.include_tasks:
        file: 'tasks/filter_incompatible_platforms.yml'
      run_once: true

    - name: 'Block: Handle installation of python3 on Debian'
      when: >-
        inventory_hostname in molecule_yml.platforms |
        map(attribute='name') |
        ansible.builtin.flatten
      block:
        - name: 'Change sources list'
          ansible.builtin.raw: |
            sed -i 's/deb.debian.org/archive.debian.org/g' /etc/apt/sources.list
          changed_when: true
          when: >-
            molecule_yml.platforms |
            selectattr('name', '==', inventory_hostname) |
            selectattr('change_sources_list', 'defined') |
            selectattr('change_sources_list', '==', true) |
            length == 1

        - name: 'Update package lists'
          ansible.builtin.raw: |
            apt-get update
          changed_when: true

        - name: 'Install Python'
          ansible.builtin.raw: |
            apt-get install -y python3
          changed_when: true

- name: 'Bootstrap Python on OpenWrt'
  hosts: 'opkg'
  gather_facts: false
  tasks:
    - name: 'Include tasks to filter incompatible platforms'
      ansible.builtin.include_tasks:
        file: 'tasks/filter_incompatible_platforms.yml'
      run_once: true

    - name: 'Block: Handle installation of python3 on Debian'
      when: >-
        inventory_hostname in molecule_yml.platforms |
        map(attribute='name') |
        ansible.builtin.flatten
      block:

        - name: 'Create opkg lock file directory'
          ansible.builtin.raw: |
            mkdir -p /var/lock
          changed_when: true

        - name: 'Include role to bootstrap Python'
          ansible.builtin.include_role:
            name: 'sscheib.openwrt_bootstrap'
          vars:
            install_full_python: true

        - name: 'Install BASH and shadow-su'
          ansible.builtin.package:
            name:
              - 'bash'
              - 'shadow-su'
            state: 'present'
...
