---
- name: 'Install Python in containers'
  hosts: 'apt'
  gather_facts: false

  tasks:
    - name: 'Update package lists'
      ansible.builtin.raw: |
        apt-get update
      changed_when: true

    - name: 'Install Python'
      ansible.builtin.raw: |
        apt-get install -y python3
      changed_when: true
...
