---
- name: 'Verify'
  hosts: 'molecule'
  gather_facts: false
  vars:
    test_file: '/tmp/test.file'
    test_content: '/tmp/test.content'

  tasks:
    - name: 'Gather information about the transfered file: {{ test_file }}'
      ansible.builtin.stat:
        path: '{{ test_file }}'
      become: true
      register: '__t_test_file'

    - name: 'Ensure specified permissions are set for: {{ test_file }}'
      ansible.builtin.assert:
        that:
          # exists
          - '__t_test_file.stat.exists is defined'
          - '__t_test_file.stat.exists'

          # owner
          - '__t_test_file.stat.pw_name is defined'
          - "__t_test_file.stat.pw_name == 'root'"

          # group
          - '__t_test_file.stat.gr_name is defined'
          - "__t_test_file.stat.gr_name == 'root'"

          # mode
          - '__t_test_file.stat.mode is defined'
          - "__t_test_file.stat.mode == '0700'"

    - name: 'Slurp file: {{ test_file }}'
      ansible.builtin.slurp:
        src: '{{ test_file }}'
      register: '__t_content_test_file'

    - name: 'Ensure content is as expected of file: {{ test_file }}'
      ansible.builtin.assert:
        that:
          - >-
            __t_content_test_file.content |
            ansible.builtin.b64decode
            ==
            'Testfile'

    - name: 'Gather information about the created file: {{ test_content }}'
      ansible.builtin.stat:
        path: '{{ test_content }}'
      become: true
      register: '__t_test_content'

    - name: 'Ensure specified permissions are set for: {{ test_content }}'
      ansible.builtin.assert:
        that:
          # exists
          - '__t_test_content.stat.exists is defined'
          - '__t_test_content.stat.exists'

          # owner
          - '__t_test_content.stat.pw_name is defined'
          - "__t_test_content.stat.pw_name == 'root'"

          # group
          - '__t_test_content.stat.gr_name is defined'
          - "__t_test_content.stat.gr_name == 'root'"

          # mode
          - '__t_test_content.stat.mode is defined'
          - "__t_test_content.stat.mode == '0600'"

    - name: 'Slurp file: {{ test_content }}'
      ansible.builtin.slurp:
        src: '{{ test_content }}'
      register: '__t_content_test_content'

    - name: 'Ensure content is as expected of file: {{ test_content }}'
      ansible.builtin.assert:
        that:
          - >-
            __t_content_test_content.content |
            ansible.builtin.b64decode
            ==
            'test'
...
