source "https://rubygems.org"

gem "just-the-docs", "0.9.0"
gem "jekyll-github-metadata", "2.16.1"
gem "jekyll-include-cache", "0.2.1", group: :jekyll_plugins
gem "html-proofer", "5.0.9", :group => :development
