source "https://rubygems.org"

gem "base64", "0.3.0"
gem "csv", "3.3.4"
gem "just-the-docs", "0.10.1"
gem "jekyll-github-metadata", "2.16.1"
gem "jekyll-include-cache", "0.2.1", group: :jekyll_plugins
gem "html-proofer", "5.0.10", :group => :development
