---
name: 'ansible-lint'
on:  # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - 'main'

    paths:
      - '.github/workflows/ansible-lint.yml'
      - 'defaults/**'
      - 'files/**'
      - 'handlers/**'
      - 'library/**'
      - 'lookup_plugins/**'
      - 'meta/**'
      - 'module_utils/**'
      - 'molecule/**'
      - 'tasks/**'
      - 'templates/**'
      - 'vars/**'

  workflow_dispatch: {}

permissions:
  contents: 'read'

jobs:
  build:
    name: 'Ansible Lint'
    runs-on: 'ubuntu-24.04'
    permissions:
      contents: 'read'
    steps:
      - name: 'Harden Runner'
        uses: 'step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7' # v2.10.1
        with:
          disable-sudo: true
          egress-policy: 'block'
          allowed-endpoints: >-
            files.pythonhosted.org:443
            github.com:443
            pypi.org:443
            raw.githubusercontent.com:443

      - name: 'Checkout code'
        uses: 'actions/checkout@d632683dd7b4114ad314bca15554477dd762a938' # v4.2.0

      - name: 'Run ansible-lint'
        uses: 'ansible/ansible-lint@3b5bee19c2102ea35bc8619795a72c5c73797fc7' # v24.9.2
...
