---
name: 'ansible-lint'
on:  # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - 'main'

    paths:
      - '.github/workflows/ansible-lint.yml'
      - 'defaults/**'
      - 'files/**'
      - 'handlers/**'
      - 'library/**'
      - 'lookup_plugins/**'
      - 'meta/**'
      - 'module_utils/**'
      - 'molecule/**'
      - 'tasks/**'
      - 'templates/**'
      - 'vars/**'

  workflow_dispatch: {}

permissions:
  contents: 'read'

jobs:
  build:
    name: 'Ansible Lint'
    runs-on: 'ubuntu-24.04'
    permissions:
      contents: 'read'
    steps:
      - name: 'Harden Runner'
        uses: 'step-security/harden-runner@cb605e52c26070c328afc4562f0b4ada7618a84e' # v2.10.4
        with:
          disable-sudo: true
          egress-policy: 'block'
          allowed-endpoints: >-
            files.pythonhosted.org:443
            github.com:443
            pypi.org:443
            raw.githubusercontent.com:443

      - name: 'Checkout code'
        uses: 'actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683' # v4.2.2

      - name: 'Run ansible-lint'
        uses: 'ansible/ansible-lint@4ce8e497d462cf73b4d4fac1e97b4ace4f317dcc' # v24.12.2
...
