---
name: 'ansible-lint'
on:  # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - 'main'

    paths:
      - '.github/workflows/ansible-lint.yml'
      - 'defaults/**'
      - 'files/**'
      - 'handlers/**'
      - 'library/**'
      - 'lookup_plugins/**'
      - 'meta/**'
      - 'module_utils/**'
      - 'molecule/**'
      - 'tasks/**'
      - 'templates/**'
      - 'vars/**'

  workflow_dispatch: {}

permissions:
  contents: 'read'

jobs:
  build:
    name: 'Ansible Lint'
    runs-on: 'ubuntu-24.04'
    permissions:
      contents: 'read'
    steps:
      - name: 'Harden Runner'
        uses: 'step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481' # v2.11.0
        with:
          disable-sudo: true
          egress-policy: 'block'
          allowed-endpoints: >-
            files.pythonhosted.org:443
            github.com:443
            pypi.org:443
            raw.githubusercontent.com:443
            www.python.org:443

      - name: 'Checkout code'
        uses: 'actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683' # v4.2.2

      - name: 'Install Python'
        uses: 'actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065' # v5.6.0
        with:
          # renovate dep: datasource=python-version versioning=python depName=python
          python-version: '3.13.3'

      - name: 'Install ansible-core and ansible-lint'
        shell: 'bash'
        run: |
          # fail if:
          # - a variable is unbound
          # - any command fails
          # - a command in a pipe fails
          # - a command in a sub-shell fails
          set -Eeuo pipefail

          # enable debug if runner runs in debug
          [[ "${{ runner.debug }}" -ne 1 ]] || {
            echo "INFO: Enabling bash trace";
            set -x;
          };

          # renovate: datasource=pypi
          pip3 install ansible-core==2.18.5

          # renovate: datasource=pypi
          pip3 install ansible-lint==25.4.0

      - name: 'Run ansible-lint'
        shell: 'bash'
        run: |
          # fail if:
          # - a variable is unbound
          # - any command fails
          # - a command in a pipe fails
          # - a command in a sub-shell fails
          set -Eeuo pipefail

          # enable debug if runner runs in debug
          [[ "${{ runner.debug }}" -ne 1 ]] || {
            echo "INFO: Enabling bash trace";
            set -x;
            declare __DEBUG="-vvvv"
          };

          cd "${GITHUB_WORKSPACE}" && ansible-lint "${__DEBUG:=}"
...
