---
name: 'Contributors'
on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - 'main'

  workflow_dispatch: {}
  schedule:
    - cron: '0 4 * * 6'

permissions:
  contents: 'read'

jobs:
  contributor_report:
    name: 'Contributor report'
    runs-on: 'ubuntu-22.04'
    permissions:
      issues: 'write'
    steps:
      - name: 'Harden Runner'
        uses: 'step-security/harden-runner@5c7944e73c4c2a096b17a9cb74d65b6c2bbafbde' # v2.9.1
        with:
          egress-policy: 'audit'
          disable-sudo: true

      - name: 'Gather contributors'
        uses: 'github/contributors@135b0430e856ade27175cbd1d4e1e11b0dd8ef95' # v1.4.3
        env:
          GH_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          LINK_TO_PROFILE: true
          REPOSITORY: '${{ github.repository }}'

      - name: 'Create issue'
        uses: 'peter-evans/create-issue-from-file@24452a72d85239eacf1468b0f1982a9f3fec4c94' # v5.0.0
        with:
          title: 'Contributors to this project ❤️'
          token: '${{ secrets.GITHUB_TOKEN }}'
          content-filepath: './contributors.md'
          assignees: 'sscheib'
...
