---
name: 'Container image retention'
on:  # yamllint disable-line rule:truthy
  schedule:
    - cron: '30 3 * * *'
  workflow_dispatch: {}

permissions:
  contents: 'read'

jobs:
  container-image-retention:
    name: 'Clean old container images'
    runs-on: 'ubuntu-22.04'
    permissions:
      packages: 'write'

    steps:
#      - name: 'Harden Runner'
#        uses: 'step-security/harden-runner@5c7944e73c4c2a096b17a9cb74d65b6c2bbafbde' # v2.9.1
#        with:
#          egress-policy: 'audit'
#          disable-sudo: true

      - uses: 'snok/container-retention-policy@4f22ef80902ad409ed55a99dc5133cc1250a0d03' # v3.0.0
        with:
          account: '${{ github.repository_owner }}'
          token: '${{ secrets.GITHUB_TOKEN }}'
          image-names: 'jekyll-build'
          cut-off: '4h'
          dry-run: true
          tag-selection: 'both'
          keep-n-most-recent: '3'
...
