---
name: 'Purge caches'
on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - 'main'

  pull_request:
    branches:
      - 'main'

    paths:
      - '.github/workflows/purge_caches.yml'

  # delete caches once a night
  schedule:
    - cron: '45 0 * * *'

permissions:
  contents: 'read'

jobs:
  check-user-permissions:
    runs-on: 'ubuntu-22.04'
    permissions:
      contents: 'read'
    outputs:
      require-result: '${{ steps.check-access.outputs.require-result }}'
    steps:
      - name: 'Harden Runner'
        uses: 'step-security/harden-runner@5c7944e73c4c2a096b17a9cb74d65b6c2bbafbde' # v2.9.1
        with:
          egress-policy: 'block'
          allowed-endpoints: >
            api.github.com:443
            github.com:443

      - name: 'Get User Permissions'
        id: 'check-access'
        uses: 'actions-cool/check-user-permission@956b2e73cdfe3bcb819bb7225e490cb3b18fd76e' # v2.2.1
        with:
          require: 'write'
          username: '${{ github.triggering_actor }}'
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'

      - name: 'Check User Permission'
        if: "steps.check-access.outputs.require-result == 'false'"
        run: |
          echo "${{ github.triggering_actor }} does not have permissions on this repo."
          echo "Current permission level is ${{ steps.check-access.outputs.user-permission }}"
          echo "Job originally triggered by ${{ github.actor }}"

  purge-caches:
    name: 'Purge caches'
    if: "needs.check-user-permissions.outputs.require-result == 'true'"
    needs: 'check-user-permissions'
    runs-on: 'ubuntu-22.04'
    permissions:
      actions: 'write'
    steps:
      - name: 'Harden Runner'
        uses: 'step-security/harden-runner@5c7944e73c4c2a096b17a9cb74d65b6c2bbafbde' # v2.9.1
        with:
          disable-sudo: true
          egress-policy: 'block'
          allowed-endpoints: >
            api.github.com:443
            github.com:443

      - name: 'Purge caches older than two days (created and accessed)'
        uses: 'actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea' # v7.0.1
        with:
          script: |
            console.log('Clearing caches');
            const caches = await github.rest.actions.getActionsCacheList({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });

            const today = new Date().getTime();
            let deletedCaches = 0;
            for (const cache of caches.data.actions_caches) {

              console.log(
                'Checking cache ' + cache.key + ' (ID: ' + cache.id + ' )'
              );

              let accessedDate = null;
              if (cache.last_accessed_at !== undefined) {
                accessedDate = Date.parse(cache.last_accessed_at);
              }

              let createdDate = null;
              if (cache.last_accessed_at !== undefined) {
                createdDate = Date.parse(cache.created_at);
              }

              // older than 2 days for either created or accessed
              if (
                (accessedDate !== null && today - accessedDate > 60 * 60 * 1000 * 24 * 2) ||
                (createdDate !== null && today - createdDate > 60 * 60 * 1000 * 24 * 2)
              ) {
                console.log(
                  'Deleting cache ' + cache.key + ' (ID: ' + cache.id + ' )'
                );

                github.rest.actions.deleteActionsCacheById({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  cache_id: cache.id,
                })

                deletedCaches++;
              }
            }
            console.log(
              'Number of deleted caches ' + deletedCaches
            );
...
