---
name: 'Purge caches'
on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - 'main'

  pull_request:
    branches:
      - 'main'

    paths:
      - '.github/workflows/purge_caches.yml'

  # delete caches once a night
  schedule:
    - cron: '45 0 * * *'

permissions:
  contents: 'read'

jobs:
  purge-caches:
    name: 'Purge caches'
    runs-on: 'ubuntu-22.04'
    permissions:
      actions: 'write'
    steps:
      - name: 'Harden Runner'
        uses: 'step-security/harden-runner@5c7944e73c4c2a096b17a9cb74d65b6c2bbafbde' # v2.9.1
        with:
          disable-sudo: true
          egress-policy: 'block'
          allowed-endpoints: >
            api.github.com:443
            github.com:443

      - name: 'Purge caches older than two days (created and accessed)'
        uses: 'MyAlbum/purge-cache@6bd5afa0f99fd6096c4e08ed0eb1730da34d78dc' # v2.2.0
        with:
          max-age: 172800
          debug: true
...
