---
name: 'Publish to Ansible Galaxy'
on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - 'main'

  workflow_dispatch: {}

permissions:
  contents: 'read'

concurrency:
  group: 'ci-${{ github.workflow }}-${{ github.ref }}'
  cancel-in-progress: false

# adding the extra_plugins as environment variables allows renovate to update the versions
env:
  # renovate dep: datasource=npm depName=@semantic-release/changelog
  semantic_release_changelog_version: '6.0.3'

  # renovate dep: datasource=npm depName=@semantic-release/git
  semantic_release_git_version: '10.0.1'

jobs:
  check-secrets:
    name: 'Check if required secrets are available'
    runs-on: 'ubuntu-24.04'
    permissions:
      contents: 'read'
    outputs:
      secrets-defined: '${{ steps.secret-check.outputs.secrets-defined }}'
    steps:
      - name: 'Harden Runner'
        uses: 'step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7' # v2.10.1
        with:
          disable-sudo: true
          egress-policy: 'block'

      - name: 'Check if all required secrets are defined'
        id: 'secret-check'
        shell: 'bash'
        run: |
          # fail if:
          # - a variable is unbound
          # - any command fails
          # - a command in a pipe fails
          # - a command in a sub-shell fails
          set -Eeuo pipefail

          (
            [[ "${{ secrets.RELEASE_TOKEN }}" != '' ]] &&
            [[ "${{ secrets.GALAXY_API_KEY }}" != '' ]]
          ) || {
            echo "secrets-defined=false" >> "${GITHUB_OUTPUT}";
            exit 0;
          };

          # secrets not empty, so assuming defined
          echo "secrets-defined=true" >> "${GITHUB_OUTPUT}";

  release:
    name: 'Publish to Ansible Galaxy'
    if: "needs.check-secrets.outputs.secrets-defined == 'true'"
    needs: 'check-secrets'
    runs-on: 'ubuntu-24.04'
    permissions:
      contents: 'write'
      issues: 'write'
      pull-requests: 'write'
    steps:
      - name: 'Harden Runner'
        uses: 'step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7' # v2.10.1
        with:
          egress-policy: 'block'
          disable-sudo: true
          allowed-endpoints: >
            api.github.com:443
            galaxy.ansible.com:443
            github.com:443
            registry.npmjs.org:443
            uploads.github.com:443

      - name: 'Checkout the repository'
        uses: 'actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683' # v4.2.2
        with:
          fetch-depth: 0
          token: '${{ secrets.RELEASE_TOKEN }}'

      - name: 'Create a semantic release'
        uses: 'cycjimmy/semantic-release-action@b1b432f13acb7768e0c8efdec416d363a57546f2' # v4.1.1
        with:
          # renovate dep: datasource=npm depName=semantic-release
          semantic_version: '24.2.0'
          extra_plugins: |
            @semantic-release/changelog@${semantic_release_changelog_version}
            @semantic-release/git@${semantic_release_git_version}
        env:
          GH_TOKEN: '${{ secrets.RELEASE_TOKEN }}'

      - name: 'Publish to Ansible Galaxy'
        uses: 'robertdebock/galaxy-action@7d89099e09f4385ec4b53eb58c0d120f1ad806dd' # 1.2.1
        with:
          galaxy_api_key: '${{ secrets.GALAXY_API_KEY }}'
          git_branch: 'main'
...
