---
name: 'Publish to Ansible Galaxy'
on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - 'main'
  workflow_dispatch: {}

permissions:
  contents: 'read'

jobs:
  check-secrets:
    name: 'Check if required secrets are available'
    runs-on: 'ubuntu-22.04'
    permissions:
      contents: 'read'
    outputs:
      secrets-defined: '${{ steps.secret-check.outputs.secrets-defined }}'
    steps:
      - name: 'Harden Runner'
        uses: 'step-security/harden-runner@5c7944e73c4c2a096b17a9cb74d65b6c2bbafbde' # v2.9.1
        with:
          disable-sudo: true
          egress-policy: 'block'

      - name: 'Check if all required secrets are defined'
        id: 'secret-check'
        shell: 'bash'
        run: |
          (
            [[ "${{ secrets.RELEASE_TOKEN }}" != '' ]] &&
            [[ "${{ secrets.GALAXY_API_KEY }}" != '' ]]
          ) || {
            echo "secrets-defined=false" >> "${GITHUB_OUTPUT}";
            exit 0;
          };

          # secrets not empty, so assuming defined
          echo "secrets-defined=true" >> "${GITHUB_OUTPUT}";

  release:
    name: 'Publish to Ansible Galaxy'
    if: "needs.check-secrets.outputs.secrets-defined == 'true'"
    needs: 'check-secrets'
    runs-on: 'ubuntu-22.04'
    permissions:
      contents: 'write'
      issues: 'write'
      pull-requests: 'write'
    steps:
      - name: 'Harden Runner'
        uses: 'step-security/harden-runner@5c7944e73c4c2a096b17a9cb74d65b6c2bbafbde' # v2.9.1
        with:
          egress-policy: 'block'
          disable-sudo: true
          allowed-endpoints: >
            api.github.com:443
            galaxy.ansible.com:443
            github.com:443
            registry.npmjs.org:443

      - name: 'Checkout the repository'
        uses: 'actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332' # v4.1.7
        with:
          fetch-depth: 0
          persist_credentials: false

      - name: 'Create a semantic release'
        uses: 'cycjimmy/semantic-release-action@cb425203a562475bca039ba4dbf90c7f9ac790f4' # v4.1.0
        with:
          semantic-release: 'v24.0.0'
          extra_plugins: |
            @semantic-release/changelog@6.0.3
            @semantic-release/git@10.0.1
        env:
          GH_TOKEN: '${{ secrets.RELEASE_TOKEN }}'

      - name: 'Publish to Ansible Galaxy'
        uses: 'robertdebock/galaxy-action@7d89099e09f4385ec4b53eb58c0d120f1ad806dd' # 1.2.1
        with:
          galaxy_api_key: '${{ secrets.GALAXY_API_KEY }}'
          git_branch: 'main'
...
